### ISSUE TITLE
option to drop sentinels

### ISSUE THREAD

**Issue by shakfu** [entangled/entangled#105]
It would be nice to have an option to tangle without sentinels (a one-way tangle so to speak) such that this:

```python
# ~\~ language=Python filename= add1.py
# ~\~ begin <<lit/MyProgram.md|program>>[init]
def add1(x):
    # ~\~ begin <<lit/MyProgram.md|content-here>>[init]
    """docstring here"""

    # ~\~ end
    return x+1
# ~\~ end
```

becomes this

```python
def add1(x):
    """docstring here"""
    return x+1
```

**Comment by jhidding** [comment]
Hi Shakeeb, this may be a bit underdocumented, but you can definitely do this already! From the command line:

    entangle tangle -a

will do what you suggest. The daemon wont work of course.

**Comment by shakfu** [comment]
Thanks Johannes, that's great to know. It's just for a final 'publishing' step so daemon is unnecessary.
