### ISSUE TITLE
Recursive template implies entangled diverging

### ISSUE THREAD

**Issue by numero-744** [entangled/entangled#106]
Hello,

Dumb user mistake I've just produced :hand_over_mouth: 

````markdown
```{.c #something}
<<something>>
```

```{.c file=something.c}
<<something>>
```
````

Current behavior (1.3.0): Entangle diverges.

Expected behavior: It would be nice to detect recursions and print an error.

Maybe duplicate of #2

**Comment by jhidding** [comment]
yes, this has been on my todo list for a while ;)

**Comment by jhidding** [comment]
Should be fixed on master branch now.
