### ISSUE TITLE
Why do files have an end marker?

### ISSUE THREAD

**Issue by flow-danny** [entangled/entangled#13]
First of all, great project!

I've just started experimenting to see what the limitations are.

Question: why do files have an end marker if it's unsafe to put things after it anyway?

## Details

With a code block as follows:
```

    ```c++ {file=test.c}
    contents here
    ```

```

This file is generated:
```c++
// ------ language="C++" file="test.c"
contents here
// ------ end
```

Now changing the `test.c` file to the following:
```c++
// ------ language="C++" file="test.c"
contents here!
// ------ end
this will get deleted
```

the markdown gets the `!` as expected.
```

    ```c++ {file=test.c}
    contents here!
    ```

```



All good so far.

Adding 2 more `!` to the markdown, and then saving, the file ends up like this:
```c++
// ------ language="C++" file="test.c"
contents here!!!
// ------ end

```

**Comment by flow-danny** [comment]
Thinking a bit more, why have a begin and end marker at all?
The Markdown file declares the C file location.

The C file doesn't refer back to the markdown source it came from... which arguably would be more useful?

**Comment by flow-danny** [comment]
The begin marker makes sense when the file is reloaded.
The end marker is for ease of parser implementation, but it would be nicer if this was omitted. However, one could argue it does prevent untangle to run before the source file is completely saved to disk.

**Comment by jhidding** [comment]
just back from holidays! Nice to see so much activity ;)
The begin marker is mainly there for getting the correct language, and a bit for redudancy. The end marker is indeed for ease of parsing.
