### ISSUE TITLE
Include language highlighting for other renderers than pandoc

### ISSUE THREAD

**Issue by sverhoeven** [entangled/entangled#21]
In info string the code snippet does not get highlighted on GitHub or VS code because they don't understand `{.python #bla}`, can we change entangled and filter to also accept a infostring that works also for GitHub and VScode

**Comment by jhidding** [comment]
This is not so easy to do. Do you have a suggestion for a syntax that works for both Github and Entangled?

**Comment by sverhoeven** [comment]
GitHub and VS Code both use string before first space in info string as the language of the code block. See https://github.com/microsoft/vscode/blob/master/src/vs/base/common/marked/marked.js#L933

So for GitHub and VS Code would be fine with 
1. `python #bla` / `cpp file=src/cgi-newtonraphson.cpp`
2. `python {#bla}` / `cpp {file=src/cgi-newtonraphson.cpp}`
3. `python {.python #bla}` / `cpp {.cpp file=src/cgi-newtonraphson.cpp}`

I like option 1 best, but not sure if you can make entangled handle them.

**Comment by sverhoeven** [comment]
For my guide I used [docsify](https://docsify.js.org/) to render the Markdown. Docsify normally uses the whole infostring as language, but it can be extended to parse the infostring see https://github.com/NLESC-JCER/cpp2wasm/blob/master/index.html#L29

**Comment by jhidding** [comment]
Ok, I tried to work with MkDocs, which is based on Python-markdown and found a syntax that would work for that:

    ```cpp file="hello.cpp"

and

    ```cpp id="print-hello"

I can add a config option to have entangled parse with custom regexes. That would fix this problem once and for all.
