### ISSUE TITLE
List code fragments that are not included anywhere

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#23]
When the `#code-fragment` is not ever mentioned, it goes to no output file at the moment.
It would be nice to print list of fragments that are not mentioned, so that author can fix it pre-emptively.

**Comment by jhidding** [comment]
I've added a `lint` command to the command-line structure (in the develop branch). By doing
`entangled lint listUnusedFragments`
you should get a list of all fragments that are not referenced in a target file. The version in the develop branch is now good to use (I use it now on entangled itself, still be careful and use git frequently) so you can try it out. Still need to backport the line-comment features though.
A nice bonus is that it can also create a dot graph by doing `entangled lint dumpToGraphViz` ;)
