### ISSUE TITLE
Option for additional pandoc filters

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#26]
By allowing an option that adds additional external pandoc filters.

This might allow user to self-service #7, #9.

**Comment by mgajda** [comment]
Note that one can use `pandoc` directly to produce PDF instead.

**Comment by jhidding** [comment]
Do you mean a filter that potentially ammends the code that is being tangled?

**Comment by jhidding** [comment]
I don't really understand what you want to achieve here. The pandoc side of Entangled is located in [entangled/filters](https://github.com/entangled/filters). I will close this issue for now, feel free to reopen it if you feel this is an issue with the daemon.
