### ISSUE TITLE
Warn about duplicate file=Target.hs statement

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#28]
If `file=Target.hs` is used for two code fragments, enTangleD will update change both when the source file is edited. This is confusing, if the name clash was accidental.

One should probably issue a warning.

**Comment by jhidding** [comment]
In the develop branch, this is resolved. Repeating a file reference will append to the same file. The behaviour is well defined.

**Comment by jhidding** [comment]
This is resolved in the develop branch. Repeating a `file=Target.hs` will append the entries in the target file. The difference between a `FileReference` and `NamedReference` is dropped. Instead, all references are what used to be `NamedReference` and the name for a `file=...` reference defaults to the filename.

**Comment by justjosias** [comment]
If this is fixed in develop, and develop is now merged into master, then shouldn't this be closed?

**Comment by jhidding** [comment]
Yes, the question is still if there should be a linter that warns about this. I think not, but I'm open to suggestions. I'll close for now.

**Comment by jhidding** [comment]
Yes, you're completely right. This should change. Out of pure interest, what is the tool you're developing?

**Comment by justjosias** [comment]
I call it "retangled". The point of it is to be simpler than entangled while still supporting the same Markdown block system. It is more of a general utility than a project-based tool so it won't support many entangled features. It is in its early stages though so there's nothing to see yet.

**Comment by jhidding** [comment]
The manual now describes the desired behaviour; I made a small change to your proposal. It should be illegal to couple a file to two different identifiers. So repeating a file should be fine as long as its done consistently.

**Comment by justjosias** [comment]
> in the second statement, the file main.rs gets associated with the #main.rs identifier implicitely.

This is good to know. What happens if the user puts `#main.rs` as an identifier directly?

**Comment by jhidding** [comment]
I'm not sure. Either a parser error or it will work as expected

**Comment by justjosias** [comment]
`-?[_a-zA-Z]+[_a-zA-Z0-9-]*` this is the Regex for valid identifiers. 

https://stackoverflow.com/a/449000/6046716

**Comment by jhidding** [comment]
Correct. You can already configure Entangled to be more strict by setting the regexes for parsing.

**Comment by mgajda** [comment]
It seems to conform to my use case, so I close this one.
The main issue was a loss of data when there were multiple `file=` stances, which is now fixed.
