### ISSUE TITLE
list/tangle subcommands do not work without existing db

### ISSUE THREAD

**Issue by sverhoeven** [entangled/entangled#49]
I tried to run the run `entangled list` and `entangled tangle -a` on files in gist https://gist.github.com/sverhoeven/30ffad9797a51fbf4ff0b45ad78a05c7

I expected the commands to tangle or list the `test.sh` file, but `test.sh` file is not generated or listed.

If I first run `entangled daemon` then remove `test.sh` file then the `list` and `tangle -a` commands work like expected. 

The `.entangled/db.sqlite` does get created when running non daemon sub commands, but only running `daemon` inserts rows.

**Comment by jhidding** [comment]
There is an explicit `entangled insert` command for that, I could add a global flag that automatically inserts all files in `watchList` before doing anything else.

**Comment by sverhoeven** [comment]
That helps, running `entangled insert -s *.md` first makes list work, but I prefer that database insert happen automatically so I don't have to think about there being a database.

**Comment by sverhoeven** [comment]
Hmm, if I make changes to a code-block in Markdown then the source code file does not get updated when running `entangled insert -s *.md && entangled tangle -a`. Only when I remove the db the source code file gets updated.

**Comment by jhidding** [comment]
That is weird, I have a unit-test that tests just that. What are the steps to reproduce?

**Comment by sverhoeven** [comment]
I updated the Docker image, seems insert now is needed and no longer a db wipe.
Reproduce with

```shell
git clone https://gist.github.com/30ffad9797a51fbf4ff0b45ad78a05c7.git .
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled insert -s *.md
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled -m tangle -a
# Here a test.sh is generated
# Edit the code block in README.md
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled -m tangle -a
# Here test.sh still has original content
```

Adding `insert` solves it

```shell
git clone https://gist.github.com/30ffad9797a51fbf4ff0b45ad78a05c7.git .
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled insert -s *.md
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled -m tangle -a
# Here a test.sh is generated
# Edit the code block in README.md
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled insert -s *.md
docker run --rm --user ${UID} -v ${PWD}:/data nlesc/entangled -m tangle -a
# Here test.sh still has original content
```

Is the second insert part of the design? I thought the database did not contain the codeblock contents itself.

**Comment by jhidding** [comment]
The database does contain the codeblock contents. The choice to use Sqlite was born out of the desire to be able to deconstruct the tangle/stitch process. I want the daemon to run on the same code as the command-line instructions. This also offers a lot of flexibility. For example:
- you can add files to the database while the daemon is running.
- future tech: check database entries against file mod times; things can get confusing if you edit code files when you forgot to run the daemon. If we would then automatically insert the markdown files those changes get wiped.
The reason why the database does contain code block content, is that line references would invalidate when files get written to.

**Comment by jhidding** [comment]
There is now a `--preinsert` flag that enables this behaviour. The preinsert mode is default when using in-memory database.
