### ISSUE TITLE
entangled.Annotate.Project puts link outside comment

### ISSUE THREAD

**Issue by sverhoeven** [entangled/entangled#53]
I set `annotate = entangled.Annotate.Project` in my config then a result JS comments looked like

```js
/* ~\~ begin <<README.md|react-state>>[0] */ project://README.md#1002
```

My web browser can not parse that.

I expected it to look like

```js
/* ~\~ begin <<README.md|react-state>>[0] project://README.md#1002 */
```

It seems to me the project directive is put after the `entangled.Comment.Block:end` instead of before.

**Comment by jhidding** [comment]
Whoops!
