### ISSUE TITLE
tangle: reference not found crashes daemon

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#59]
When we run the daemon, we expect to change and improve the source file.
It will often happen that references are missing, we need to improve them, and get the update.
However, latest version of enTangleD crashes when reference is not found, instead of watching for changes and updating the errors list:
```
Entangled, version 1.1.0: https://entangled.github.io/

entangled: TangleError "TangleError \"reference not found: ReferenceName {unReferenceName = \\\"treelike\\\"}\""
```

Commit `a60d8d6acbf4b622bb92873c9535c627158a84ca`.
We can also note that the error is printed with unnecessary double-quoting and double-escaping `\\\"`

**Comment by jhidding** [comment]
To fix: move error handling in the daemon up one function. This also fixes a second  problem: when stitching fails, the post-stitch tangle is still being run, overwriting changes in the target file.

**Comment by mgajda** [comment]
It seems this is an instance of a general problem where exception crashes entire program instead of reporting error and continuing.

My talk on recommended error handling in data pipelines may help: https://www.youtube.com/watch?v=KY27LsV11Rg&t=51s

Basic idea to handle it gracefully in a program that handles multitude of inputs like enTangleD does:
1. Add a `WriterT` monad transformer that gathers all errors.
2. Instead of using `forM`/`mapM`/`mapM . mapMaybe` use `forData` construct that gathers correctly processed outputs, and also gathers list of errors into a log inside `WriterT`:
```{.haskell}
mapData :: (Monad m, MonadWriter e m, MonadCatch m) => (a -> m b) -> [a] -> m [b]
mapData f =  concat
         <$> mapM (f >>= return ([]:)
                     `catch` (\issue -> tell >> return []))
```

In case of `enTangleD` we do not even need `WriterT` - we can just log errors with `IO.hPutStrLn stderr`. That means that we replace `mapM` with:

```{.haskell}
mapData :: (a -> IO b) -> [a] -> IO [b]
mapData f =  concat
         <$> mapM (f >>= return ([]:)
                     `catch` (\issue -> hPrint stderr >> return []))
```

This solution would be relevant for: #73, #59 and likely many other cases where `throwM` should be caught generically in the encompassing `forM` or `mapM`. This likely would improve error handling in most cases of `mapM` and `mapMaybe`.

**Comment by jhidding** [comment]
This specific issue should be fixed in master now.
