### ISSUE TITLE
In-Memory DB

### ISSUE THREAD

**Issue by MyriaCore** [entangled/entangled#81]
Hi!

So this is super related to #66, since it was discussed quite a bit, but an in-memory database would be a great first step towards operation of entangled without the need of environmental dependencies.

Makes sense to have a seperate issue for this IMO since #66 can be thought of better as a super-issue or epic of sorts.

**Comment by mgajda** [comment]
What if you just try to use `":memory:"` instead of database file path?

**Comment by jhidding** [comment]
There's a good possibility that that will just work. I just never tried.

**Comment by MyriaCore** [comment]
I didn't know that `:memory:` was already in the code. Maybe that should be documented somewhere in the manual.

**Comment by jhidding** [comment]
Using `None Text` as database, which is also the default, has the same effect of in-memory database.
