### ISSUE TITLE
Robust configuration format

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#84]
Currently we have a configuration format that is very fragile and is likely to break between versions:
```
$ entangled daemon
entangled: 
Error: Expression doesn't match annotation

{ + syntax : …
, …
}

 1│ (/home/m/Projects/less-arbitrary/entangled.dhall).entangled : { version : Text
 2│ , languages :
 3│     List
 4│       { name : Text
 5│       , identifiers : List Text
 6│       , comment : < Line : Text | Block : { start : Text, end : Text } >
 7│       }
 8│ , watchList : List Text
 9│ , database : Optional Text
10│ , annotate : < Naked | Standard | Project >
11│ , lineDirectives : List { name : Text, format : Text }
12│ , useLineDirectives : Bool
13│ }

(input):1:1
```

To compound on this problem, `dhall` does not provide narrow error location, and instead puts on the user to debug it.
At times even running `entangled config` to generate a fresh configuration will not help.

**Comment by jhidding** [comment]
Could you be more precise in the cases where it fails? I find that Dhall offers excellent support for versioning by forcing you to import the schema. I have made breaking changes to the config format two times now, where old versions are still being read correctly and brought up-to-date using default settings:

https://github.com/entangled/entangled/blob/df0e5c0c46ec0e80dc842f827b6eb3a4a518debd/src/Config.hs#L17-L19

That means, if you have a older config file it should still work with newer versions of entangled.

**Comment by mgajda** [comment]
The last time was when I compiled out of repo version, and upgraded configuration then tried to use older version.
I fixed it be upgrading to the latest 1.2.

The time before was when there was a missing field in between 1.0 and 1.2.

**Comment by jhidding** [comment]
so, sure the config is not two way compatible, but you should still be able to use older config files with newer versions. The thing is that Dhall does a lot for me that I don't have to think about: validation, defaults, limited programmability, having data standards... I agree that some of the error messages could improve, especially where it concerns the link with  Haskell data structures.

So let me get this straight: you tried to run an older entangled with too new a config. We should check for that when reading the input.

**Comment by jhidding** [comment]
I'm still not sure what behaviour you're expecting. From what you describe, you were using an older version of Entangled with a newer config format. I can see no way how to anticipate future changes in config format like that. Closing this for now.
