### ISSUE TITLE
Unused references were a feature, not a bug

### ISSUE THREAD

**Issue by vizanto** [entangled/entangled#87]
It's been a while since i've updated, as I've been using my fork :-)

I mentioned in https://github.com/entangled/entangled/pull/16#issuecomment-575068027 that we use entangled to build our software in layers, where if done correctly -in theory- you can build working software building "up to" a layer. Each layer adds to the system.

Now that unused references are *illegal* this doesn't work as expected. In the old version I would have some `<<reference>>`s as extension point for upper layers to build on. The output would just be a blank line if unused, but that's what I wanted.

Any way to get this back, or a good workaround? 😄

**Comment by jhidding** [comment]
Yes, I will make it a priority to fix this.

**Comment by vizanto** [comment]
Any news on this? 🤔

**Comment by jhidding** [comment]
Sorry, I've had very little time the last few months. Let's see what I can do this weekend.

**Comment by jhidding** [comment]
In the latest master branch, you should just get a warning now.

**Comment by vizanto** [comment]
Wow, that was sudden 😄  Thanks!!
