### ISSUE TITLE
Workflows: get gnuplot example to work

### ISSUE THREAD

**Issue by jhidding** [entangled/entangled#9]
Supporting workflows is a task in itself, but for starters, it would be nice to get a Gnuplot script to expand into a plot.

**Comment by mgajda** [comment]
There is a workaround:
Run `pandoc` on `inotifywait` tool:
```sh
while inotifywait ${NAME}.md ${NAME}.bib -e modify,close_write,attrib,access; do make; don
```
Then one can make a typical `Makefile` for `pandoc`:
```
out/doc.pdf: doc.md
        pandoc --filter pandoc-filter-gnuplot doc.md -o doc.pdf
```
