### ISSUE TITLE
Nested references used in multiple files duplicate after stitching (regression)

### ISSUE THREAD

**Issue by vizanto** [entangled/entangled#91]
We use nested references as extension points to allow configuration and boilerplate be shared between different markdown and target files. Lower layers (markdown) define some places to put config and upper layers add to it.

When `touch`ing any of the output files (`a.ts` or `b.ts`) the daemon does:

```
* [15:04:35] stitching on `a.ts`
    * Writing 'nested-bug.md'

* [15:04:35] tangling after stitch `a.ts`
    * Writing 'a.ts'
    * Writing 'b.ts'
```

and duplicates entire code block references in the markdown:

```md
<<shared/setting>>
<<shared/setting>>
<<shared/setting>>
...
```

---

Here's an example that breaks on master:

- [nested-bug.md](https://github.com/entangled/entangled/files/6892519/nested-bug.md)
- [nested-bug-trigger.md](https://github.com/entangled/entangled/files/6892460/nested-bug-trigger.md)
- [entangled.dhall](https://github.com/entangled/entangled/files/6892473/entangled.dhall.txt)

**Comment by flow-luka** [comment]
The duplication also affects the code block contents.

The problem seems to manifest itself when two snippets use exactly the same name in two different .md files.

**Comment by jhidding** [comment]
Sorry that this took a while to fix. If all went well the issue should be dealt with now in master branch, soon in a new release (1.3.0).

**Comment by vizanto** [comment]
Wonderful, thanks!!

**Comment by flow-danny** [comment]
So I finally got around to trying, indeed no more duplicates...

but tangling twice the references update from `[0]` to `[1]` after which editing a file drops entire sections because `[0]` is now missing...

**Comment by vizanto** [comment]
So I finally got around to trying, indeed no more duplicates...

but tangling twice the references update from `[0]` to `[1]` after which editing a file drops entire sections because `[0]` is now missing...

**Comment by flow-danny** [comment]
To reproduce, I've added to `nested-bug.md`:

````
C:

```ts {file=c.ts}
<<shared/setting>>
```
````

and then edited `c.ts`.  All you have to do is save `c.ts` once or twice.

Attached the files for your convenience: 
[testfiles.zip](https://github.com/entangled/entangled/files/8873709/testfiles.zip)
.

**Comment by vizanto** [comment]
To reproduce, I've added to `nested-bug.md`:

````
C:

```ts {file=c.ts}
<<shared/setting>>
```
````

and then edited `c.ts`.  All you have to do is save `c.ts` once or twice.

Attached the files for your convenience: [testfiles.zip](https://github.com/entangled/entangled/files/8873709/testfiles.zip).
