### ISSUE TITLE
Feature request: Config options for line annotations

### ISSUE THREAD

**Issue by PPKFS** [entangled/entangled#96]
I went to your talk at the FP Dag and thought Entangled was a great idea, and it's been lovely to use (currently in tandem with `mdbook` for static site generation as bootstrap had difficulties with multiple pages).

One thing that would be nice is to be able to change the format of line number separators when the `entangled.Annotate.Project` option is set. Right now, it's always `#`:

```
-- can't jump to markdown with this 
-- ~\~ begin <<lit/effects/say.md#40|interpret-say-io>>[0]
```
whereas VSCode and the "Jump to line number" extension expect a `:`:
```
-- but can with this!
-- ~\~ begin <<lit/effects/say.md:40|interpret-say-io>>[0]
```

I may have a dig and see if I can contribute to the project :)

**Comment by jhidding** [comment]
I added an option called `lineNumberSeparator` that currently does nothing. The person that contributed the `Project` annotation idea actually did so for another VsCode plugin (https://github.com/KyleDavidE/vscode-project-links). Your proposal shouldn't break that. How should this work *exactly*?

**Comment by flow-danny** [comment]
Oh if this can be done without a plugin even better!

**Comment by PPKFS** [comment]
> I added an option called `lineNumberSeparator` that currently does nothing. The person that contributed the `Project` annotation idea actually did so for another VsCode plugin (https://github.com/KyleDavidE/vscode-project-links). Your proposal shouldn't break that. How should this work _exactly_?

Oh - if there already exists a plugin that works with it currently, then everything is fine. I got somewhat lost in VSCode's ability to not be clear about when it does/does not allow make links jumpable. Thank you!
